use_frameworks!

target 'ESportsGameClient_Example' do
#  pod 'ESportsGameClient', :path => '../'
  pod 'ESportsGameClient', :git => 'https://github.com/jrangelr4pid/test.git', :branch => 'master'

  target 'ESportsGameClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
